applications:
- name: fraudvalidationservice
  instances: 2
  disk_quota: 650M
  memory: 1G
  path: ../../../target/FraudValidation-0.0.1-SNAPSHOT.jar
  services:
   - belk_dom_createupdate
   - belk_dom_orderdetails
  env:
    spring.profiles.active: prod
